# Generated by Django 5.0.3 on 2024-04-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('photo', models.ImageField(upload_to='images')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('is_poblished', models.BooleanField(default=True)),
            ],
        ),
    ]
